version: '3.8'

services:
  app:
    image: apistackoverflowquestions-app:latest
    container_name: StackOverFlowAPP
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: stackoverflow
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: